services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: anime_webapp-frontend-1

    ports:
      - "8001:3000"

    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: "1.0"

    restart: unless-stopped